services:
  inventory_database:
    image: postgres:15-alpine
    container_name: inventory_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"  
    restart: unless-stopped
    networks:
      - app_network

volumes:
  pgdata:

networks:
  app_network:
    driver: bridge
